sudo: required
language: c
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
arch:
  packages:
    # pacman packages
    - python
    - perl
    - ccache
    - tree
    # aur packages
    # - gimp-git
    - gimp-extras
    #- gimp-plugin-saveforweb
  script:
    #- "pacman -Qi gimp-git"
    - alias
    - pwd
    - echo "$HOME"
    - mkdir "$HOME/ARCHROOT_PACKAGES"
    - ls -lash $HOME
    - cd "$HOME/ARCHROOT_PACKAGES"
    - for i in `find ~ -nowarn -type f -name '*.pkg.tar.xz'`; do echo "--> $i"; cp "$i" "$HOME/ARCHROOT_PACKAGES"; done
    - repo-add gimp-git.db.tar.xz *.pkg.tar.xz
    
    - pwd
    - ls -lash
script:
  - "curl -O https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh"
  # insert «sed -i 's/!ccache/ccache/' $ARCH_TRAVIS_CHROOT/etc/makepkg.conf» after the «add mirror» comment
  - "sed -i '/add mirror/a\ \ as_root \"sed -i '\''s/!ccache/ccache/'\'' $ARCH_TRAVIS_CHROOT/etc/makepkg.conf\"' ./arch-travis.sh"
  # add ccache to the base initial packages for good measure (so that pacaur gets correctly generated too)
  - "sed -i 's/base-devel/base-devel\" \"ccache/' ./arch-travis.sh"
  - "bash ./arch-travis.sh"
  - "ls -lash"
  - cd $HOME
  - "ls -lash $HOME"
  - "ls -lash $HOME/.cache"
  - pwd
  - git clone --branch='gh-pages' https://swyter:$personal_token@github.com/Swyter/gimp-git /tmp/target-crap
  - cd /tmp/target-crap
  - git branch -a
  - ls -lash
  - git add *.tar.xz
  - if [ -n "`git status --porcelain`" ]; then return; fi
  - cp "$HOME/root.x86_64/home/travis/ARCHROOT_PACKAGES/*" .
  - ls -lash $HOME/root.x86_64/home/travis/ARCHROOT_PACKAGES
  - for i in `find "$HOME/root.x86_64/home/travis/" -nowarn -type f -name '*.pkg.tar.xz'`; do echo "--> $i"; cp "$i" .; done
  - git config --global user.email "swyterzone+gimp-git-bot@gmail.com"
  - git config --global user.name  "travis-ci bot"
  - git commit -am "Committed by travis-ci on `date`"
  - git push origin gh-pages
