sudo: required
language: c
cache:
  directories:
  - .autoconf
  - .cache
  - .ccache
arch:
  packages:
    # pacman packages
    - python
    - perl
    - ccache
    - tree
    # aur packages
    - gimp-git
  script:
    - "ls /var/cache/pacman/pkg/"
    - "tree /tmp"
    - "find / -type f -name '*.pkg.tar.xz'"
    - "pacman -Qi gimp-git"
    - ls "~/.ccache"
script:
  - "curl -O https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh"
  # insert «sed -i 's/!ccache/ccache/' $ARCH_TRAVIS_CHROOT/etc/makepkg.conf» after the «add mirror» comment
  - "sed -i '/add mirror/a\ \ as_root \"sed -i '\''s/!ccache/ccache/'\'' $ARCH_TRAVIS_CHROOT/etc/makepkg.conf\"' ./arch-travis.sh"
  # add ccache to the base initial packages for good measure (so that pacaur gets correctly generated too)
  - "sed -i 's/base-devel/base-devel\" \"ccache/' ./arch-travis.sh"
  - "bash ./arch-travis.sh"
