sudo: required
language: c
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
arch:
  packages:
    # pacman packages
    - python
    - perl
    - ccache
    - tree
    # aur packages
    # - gimp-git
    - gimp-extras
    #- gimp-plugin-saveforweb
  script:
    - "find ~ -nowarn -type f -name '*.pkg.tar.xz'`"
    - "find $HOME -nowarn -type f -name '*.pkg.tar.xz'`"
    - ls -lash .
    - pwd
    - ls -lash $HOME
    - whoami
    - tree .
    - tree $HOME
    #- "packages=`find ~/.cache/pacaur -nowarn -type f -name '*.pkg.tar.xz'`"
    #- "echo $packages"
    #- "pacman -Qi gimp-git"
    #- "cd /tmp"
    #- "git clone -b gh-pages https://swyter:$personal_token@github.com/Swyter/gimp-git && cd gimp-git"
    #- "for i in $packages; do cp \"$i\" .; done"
    #- "repo-add gimp-git.db.tar.xz *.pkg.tar.xz"
    #- "git add *"
    #- "git commit -am \"Committed by travis-ci on `date`\" && git push"
script:
  - "curl -O https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh"
  # insert «sed -i 's/!ccache/ccache/' $ARCH_TRAVIS_CHROOT/etc/makepkg.conf» after the «add mirror» comment
  - "sed -i '/add mirror/a\ \ as_root \"sed -i '\''s/!ccache/ccache/'\'' $ARCH_TRAVIS_CHROOT/etc/makepkg.conf\"' ./arch-travis.sh"
  # add ccache to the base initial packages for good measure (so that pacaur gets correctly generated too)
  - "sed -i 's/base-devel/base-devel\" \"ccache/' ./arch-travis.sh"
  - "bash ./arch-travis.sh"
  - "ls -lash"
  - "ls -lash $HOME/.cache"
  - "ls -lash .cache"
  - sudo apt-get -qq update
  - sudo apt-get install -y tree
  - tree .
  - tree $HOME
  - tree .cache
