sudo: required
language: c
arch:
  packages:
    # pacman packages
    - python
    - perl
    # aur packages
    - gimp-git
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
